### ISSUE TITLE
[Suggestion]: upgrade version of package

### ISSUE THREAD

**Issue by GANFI** [kiwilan/php-archive#46]
### What happened?

Hi!
Could you upgrade version of package? 
I want to use new features of your package like binary path and etc, but I can't do it because current git version contains 54 new commits to main branch since last release 

### How to reproduce the bug

Install package via composer 

### Package Version

2.2.0

### PHP Version

8.2.0

**Comment by ewilan-riviere** [comment]
Sorry for inconvenience, you can now use `2.3.0`.

**Comment by GANFI** [comment]
Thanks
